import { TypeName } from "./TypeName";

export const DATA = [
    {
      id: '1',
      uri: 'ic_achievement',
      title: 'Wake and bake',
      description: 'You baked Your first cookie',
      type: TypeName.LEVEL,
      count: 1,
    },
    {
      id: '2',
      uri: 'ic_baloons',
      title: 'You have talent',
      description: 'You found ballons',
      type: TypeName.LEVEL,
      count: 2,
    },
    {
      id: '3',
      uri: 'ic_heart',
      title: 'You really like that',
      description: 'You put all heart in that',
      type: TypeName.LEVEL,
      count: 4,
    },
    {
      id: '4',
      uri: 'ic_achievement_tab',
      title: 'New achievment',
      description: 'You got new achievment',
      type: TypeName.LEVEL,
      count: 6,
    },
    {
      id: '5',
      uri: 'ic_party',
      title: 'You reealy like clicking',
      description: 'Time for clicking party',
      type: TypeName.LEVEL,
      count: 8,
    },
    {
      id: '6',
      uri: 'ic_fireworks',
      title: 'Time for fireworks',
      description: 'It is show time',
      type: TypeName.LEVEL,
      count: 10,
    },
    {
      id: '7',
      uri: 'ic_baloons',
      title: 'You have talent',
      description: 'You found ballons',
      type: TypeName.LEVEL,
      count: 12,
    },
    {
      id: '8',
      uri: 'ic_heart',
      title: 'You really like that',
      description: 'You put all heart in that',
      type: TypeName.LEVEL,
      count: 14,
    },
    {
      id: '9',
      uri: 'ic_party',
      title: 'You reealy like clicking',
      description: 'Time for clicking party',
      type: TypeName.LEVEL,
      count: 15,
    },
    {
      id: '10',
      uri: 'ic_fireworks',
      title: 'Time for fireworks',
      description: 'It is show time',
      type: TypeName.LEVEL,
      count: 20,
    },
    {
      id: '11',
      uri: 'ic_second_fireworks',
      title: 'Great job',
      description: 'You colected ten cookies',
      type: TypeName.COOKIES,
      count: 10,
    },
    {
      id: '12',
      uri: 'ic_party_man',
      title: 'Keep going',
      description: 'You making great job',
      type: TypeName.COOKIES,
      count: 20,
    },
    {
      id: '13',
      uri: 'ic_start_user',
      title: 'You deserve stars',
      description: 'You deserve stars',
      type: TypeName.COOKIES,
      count: 50,
    },
    {
      id: '14',
      uri: 'ic_star',
      title: 'Your star',
      description: 'Star for You',
      type: TypeName.COOKIES,
      count: 70,
    },
    {
      id: '15',
      uri: 'ic_king',
      title: 'King',
      description: 'The King of baking cookies',
      type: TypeName.COOKIES,
      count: 100,
    },
    {
      id: '16',
      uri: 'ic_achievement',
      title: 'New achievement',
      description: 'You have got new achievement',
      type: TypeName.COOKIES,
      count: 150,
    },
    {
      id: '17',
      uri: 'ic_gear',
      title: 'Factory',
      description: 'You work like a factory',
      type: TypeName.COOKIES,
      count: 200,
    },
    {
      id: '18',
      uri: 'ic_cheers',
      title: 'Almost done',
      description: 'You colect allmost all achievements',
      type: TypeName.COOKIES,
      count: 250,
    },
    {
      id: '19',
      uri: 'ic_normal_heart',
      title: 'Love clicking',
      description: 'You really like clecking',
      type: TypeName.COOKIES,
      count: 320,
    },
    {
      id: '20',
      uri: 'ic_daimond',
      title: 'Winner',
      description: 'You colect all achievements',
      type: TypeName.COOKIES,
      count: 350,
    },
];