import { TypeName } from "./TypeName";

export const DATA = [
    {
      id: '1',
      uri: 'ic_achievement',
      title: 'Your first baking',
      description: 'You baked Your first cookie',
      type: TypeName.LEVEL,
      count: 1,
    },
    {
      id: '2',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.LEVEL,
      count: 2,
    },
    {
      id: '3',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.LEVEL,
      count: 4,
    },
    {
      id: '4',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.LEVEL,
      count: 6,
    },
    {
      id: '5',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.LEVEL,
      count: 8,
    },
    {
      id: '6',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.LEVEL,
      count: 10,
    },
    {
      id: '7',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.LEVEL,
      count: 12,
    },
    {
      id: '8',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.LEVEL,
      count: 14,
    },
    {
      id: '9',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.LEVEL,
      count: 15,
    },
    {
      id: '10',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.LEVEL,
      count: 20,
    },
    {
      id: '11',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.COOKIES,
      count: 10,
    },
    {
      id: '12',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.COOKIES,
      count: 20,
    },
    {
      id: '13',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.COOKIES,
      count: 50,
    },
    {
      id: '14',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.COOKIES,
      count: 70,
    },
    {
      id: '15',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.COOKIES,
      count: 100,
    },
    {
      id: '16',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.COOKIES,
      count: 150,
    },
    {
      id: '17',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.COOKIES,
      count: 200,
    },
    {
      id: '18',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.COOKIES,
      count: 250,
    },
    {
      id: '19',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.COOKIES,
      count: 320,
    },
    {
      id: '20',
      uri: 'ic_achievement',
      title: '',
      description: '',
      type: TypeName.COOKIES,
      count: 350,
    },
];